
import java.awt.ComponentOrientation;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class TaquinUI extends javax.swing.JFrame
{

    ArrayList<JButton> buttons;
    int[][] matrixGrid;
    Map<Integer,Map<Integer,Integer>> matrixButtons;
    int n = 3;
    
    /**
     * Inicializacion de la matriz: matrixGrid
     */
    public void initMatrix(){
        int k = 0;
        matrixGrid = new int[n][n];
        matrixButtons = new HashMap<>();
        for(int i = 0; i < n*n;i++)
            matrixButtons.put(i, new HashMap<>());
        for(int i = 0;i < n;i++){
            for(int j = 0;j<n;j++){
                matrixGrid[i][j] = 1;
                matrixButtons.get(k).put(i, j);
                k++;
            }
        }
        matrixGrid[n-1][n-1] = 0;  // cero significa vacio
    }
    
    /**
     * Creates new form TaquinUI
     */
    public TaquinUI() {
        initComponents();
        buttons = new ArrayList<>();
        
        initMatrix();
        
        //TODO: ver GridBagLayout
        getContentPane().setLayout(new GridLayout(n, n));
        
        for (int i = 0; i < (n * n)-1; ++i)
        {
            //Las imagenes son opcionales, se deben colocar en la carpeta "imagenes" y su nombre debe ser "1", "2", ..., "n", y deben estar en formato "jpg".
            buttons.add(new JButton(Integer.toString(i+1), new ImageIcon("images/" + Integer.toString(i+1) + ".jpg")));
            buttons.get(i).addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    buttonPerformed(e);
                }
            });
            add(buttons.get(i));
        }
    }
    
    private void buttonPerformed(ActionEvent e){
        int x,y;
        JButton button = (JButton)e.getSource();
        Set<Integer> set = matrixButtons.get(Integer.parseInt(button.getText())-1).keySet();
        y = (Integer)(set.toArray())[0];
        x = matrixButtons.get(Integer.parseInt(button.getText())-1).get(y);
        System.out.println(x+" "+y);
        if( y!=0 && matrixGrid[y-1][x]==0){ // UP
            System.out.println("arriba");
            matrixGrid[y-1][x] = 1;
            matrixGrid[y][x] = 0;
            matrixButtons.get(Integer.parseInt(button.getText())-1).clear();
            matrixButtons.get(Integer.parseInt(button.getText())-1).put(y-1,x);
            button.setLocation(button.getX(), button.getY() - button.getHeight());  // Movimiento hacia arriba
        }else{
            if( x!=0 && matrixGrid[y][x-1]==0){ // Left
                System.out.println("izquierda");
                matrixGrid[y][x-1] = 1;
                matrixGrid[y][x] = 0;
                matrixButtons.get(Integer.parseInt(button.getText())-1).clear();
                matrixButtons.get(Integer.parseInt(button.getText())-1).put(y,x-1);
                button.setLocation(button.getX() - button.getWidth(), button.getY());  // Movimiento hacia la izquierda
            }else{
                if( y!=(n-1) && matrixGrid[y+1][x]==0){ // Down
                    System.out.println("abajo");
                    matrixGrid[y+1][x] = 1;
                    matrixGrid[y][x] = 0;
                    matrixButtons.get(Integer.parseInt(button.getText())-1).clear();
                    matrixButtons.get(Integer.parseInt(button.getText())-1).put(y+1,x);
                    button.setLocation(button.getX(), button.getY()+button.getHeight());  // Movimiento hacia abajo
                }else{
                    if( x!=(n-1) && matrixGrid[y][x+1]==0){ // Right
                        System.out.println("derecha");
                        matrixGrid[y][x+1] = 1;
                        matrixGrid[y][x] = 0;
                        matrixButtons.get(Integer.parseInt(button.getText())-1).clear();
                        matrixButtons.get(Integer.parseInt(button.getText())-1).put(y,x+1);
                        button.setLocation(button.getX() + button.getWidth(), button.getY());  // Movimiento hacia la derecha
                    }
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaquinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaquinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaquinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaquinUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaquinUI ui = new TaquinUI();
                ui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
